mongo-url = "mongodb://toodai:toodai@mongo:27017/toodai?authSource=toodai"
elasticsearch-urls = ["http://es01:9200"]
elasticsearch-user = "elastic"
elasticsearch-password = "password"
direct-read-namespaces = ["toodai.bookmark"]
change-stream-namespaces = ["toodai.bookmark"]

[[mapping]]
namespace = "toodai.bookmark"
index = "bookmarks"

[[script]]
namespace = "toodai.bookmark"
path = "./scripts/transform.js"
routing = true